import type { KnowledgeArticle, KnowledgeArticleCategory, KnowledgeArticleStatus, KnowledgeReadingLevel } from '@cane-corso-platform/contracts';
import type { Locale } from '@/lib/i18n';

type KnowledgeArticleSeed = Omit<KnowledgeArticle, 'locale'>;

export const knowledgeArticleCategoryLabels: Record<Locale, Record<KnowledgeArticleCategory, string>> = {
  en: {
    history: 'History',
    standard: 'Official standard',
    health: 'Health',
    training: 'Training',
    care: 'Care',
    breeding: 'Responsible breeding',
    travel: 'Travel & transport',
    adoption: 'Adoption & rescue',
    platform: 'USG platform',
  },
  bg: {
    history: 'История',
    standard: 'Официален стандарт',
    health: 'Здраве',
    training: 'Обучение',
    care: 'Грижа',
    breeding: 'Отговорно развъждане',
    travel: 'Пътуване и транспорт',
    adoption: 'Осиновяване и търси дом',
    platform: 'USG платформа',
  },
  it: {
    history: 'Storia',
    standard: 'Standard ufficiale',
    health: 'Salute',
    training: 'Training',
    care: 'Cura',
    breeding: 'Allevamento responsabile',
    travel: 'Viaggio e trasporto',
    adoption: 'Adozione e rescue',
    platform: 'Piattaforma USG',
  },
};

export const knowledgeArticleStatusLabels: Record<Locale, Record<KnowledgeArticleStatus, string>> = {
  en: {
    draft: 'Draft',
    pending_review: 'Pending review',
    published: 'Published',
    archived: 'Archived',
  },
  bg: {
    draft: 'Чернова',
    pending_review: 'Чака преглед',
    published: 'Публикувана',
    archived: 'Архивирана',
  },
  it: {
    draft: 'Bozza',
    pending_review: 'In revisione',
    published: 'Pubblicata',
    archived: 'Archiviata',
  },
};

export const knowledgeReadingLevelLabels: Record<Locale, Record<KnowledgeReadingLevel, string>> = {
  en: {
    basic: 'Basic',
    advanced: 'Advanced',
    expert: 'Expert',
  },
  bg: {
    basic: 'Основно',
    advanced: 'Разширено',
    expert: 'Експертно',
  },
  it: {
    basic: 'Base',
    advanced: 'Avanzato',
    expert: 'Esperto',
  },
};

export const knowledgeArticleAdminModelFields: Record<Locale, readonly string[]> = {
  en: [
    'Title',
    'Slug',
    'Language',
    'Category',
    'Short excerpt',
    'Article sections',
    'Key facts',
    'Safety warnings',
    'Source references',
    'Reviewed by admin',
    'Last reviewed label',
    'Status: Draft / Pending / Published / Archived',
    'Featured flag',
    'Reading level',
    'Related articles',
  ],
  bg: [
    'Заглавие',
    'Адрес на статията',
    'Език',
    'Категория',
    'Кратко описание',
    'Секции на статията',
    'Ключови факти',
    'Важни предупреждения',
    'Източници',
    'Прегледано от админ',
    'Последен преглед',
    'Статус: Чернова / Чака преглед / Публикувана / Архивирана',
    'Отличена статия',
    'Ниво на четене',
    'Свързани статии',
  ],
  it: [
    'Titolo',
    'Slug',
    'Lingua',
    'Categoria',
    'Estratto breve',
    'Sezioni articolo',
    'Fatti principali',
    'Avvisi importanti',
    'Fonti',
    'Revisionato da admin',
    'Ultima revisione',
    'Stato: Bozza / In revisione / Pubblicata / Archiviata',
    'In evidenza',
    'Livello di lettura',
    'Articoli correlati',
  ],
};

const sharedSources = {
  fciStandard: {
    label: 'FCI Standard N°343 — Cane Corso Italiano',
    href: 'https://www.fci.be/nomenclature/standards/343g02-en.pdf',
  },
  fciBreed: {
    label: 'FCI breed nomenclature — Cane Corso Italiano (343)',
    href: 'https://www.fci.be/en/nomenclature/ITALIAN-CANE-CORSO-343.html',
  },
  akcStandard: {
    label: 'AKC Official Standard of the Cane Corso',
    href: 'https://images.akc.org/pdf/breeds/standards/CaneCorso.pdf',
  },
  ukcStandard: {
    label: 'UKC Cane Corso Italiano Breed Standard',
    href: 'https://www.ukcdogs.com/cane-corso-italiano',
  },
  ccaaJudgesManual: {
    label: "CCAA Judge's Manual 2022",
    href: 'https://www.canecorso.org/uploads/1/1/8/2/118210967/2022_ccaa_judges_manual.pdf',
  },
  akcBreed: {
    label: 'American Kennel Club — Cane Corso breed information',
    href: 'https://www.akc.org/dog-breeds/cane-corso/',
  },
  ccaaHealth: {
    label: 'Cane Corso Association of America — AKC CHF + CHIC health testing',
    href: 'https://www.canecorso.org/akc-canine-health-foundation--chic.html',
  },
  ofaChic: {
    label: 'Orthopedic Foundation for Animals — CHIC browse by breed',
    href: 'https://ofa.org/chic-programs/browse-by-breed/',
  },
} as const;

const articleSeeds: Record<Locale, readonly KnowledgeArticleSeed[]> = {
  en: [
    {
      slug: 'cane-corso-history-and-identity',
      status: 'published',
      category: 'history',
      title: 'Cane Corso history and identity',
      excerpt: 'A concise owner-readable article about the breed name, Italian roots, guardian heritage, and why history should guide responsible ownership.',
      reviewedLabel: 'USG editorial foundation • Step 30',
      readingLevel: 'basic',
      featured: true,
      tags: ['History', 'Italy', 'Identity'],
      heroNote: 'History should support responsibility. It should not turn the Cane Corso into a status symbol or a decorative luxury object.',
      sections: [
        {
          heading: 'The name carries responsibility',
          body: 'Cane Corso is not a generic large dog label. It represents a serious Italian guardian breed with a working background, a strong public presence, and a duty of responsible handling.',
          bullets: ['Use Cane Corso naming consistently.', 'Explain identity before promotion.', 'Connect heritage to safe ownership.'],
        },
        {
          heading: 'From heritage to modern platform trust',
          body: 'USG should treat history as a trust layer. A public profile, registry record, or certificate becomes stronger when the owner understands the breed behind the document.',
        },
      ],
      keyFacts: [
        { label: 'Origin frame', value: 'Italy / Southern Italy orientation' },
        { label: 'Identity role', value: 'Guardian and utility heritage' },
        { label: 'USG use', value: 'Educational context before registry visibility' },
      ],
      warnings: [
        'Do not present history as proof of quality for an individual Cane Corso.',
        'Do not use heritage copy to encourage risky public behavior or status-symbol ownership.',
      ],
      sourceReferences: [sharedSources.fciStandard, sharedSources.fciBreed, sharedSources.akcBreed],
      relatedSlugs: ['official-standard-owner-reading', 'training-socialization-and-public-safety'],
      adminNotes: 'Safe public article seed. Future admin editor can replace sections, keep source discipline, and preserve published-only visibility.',
    },
    {
      slug: 'official-standard-owner-reading',
      status: 'published',
      category: 'standard',
      title: 'How owners should read the official standard',
      excerpt: 'A practical bridge between official breed-standard facts and owner-friendly explanations without replacing judge education or kennel-club material.',
      reviewedLabel: 'USG editorial foundation • Step 30',
      readingLevel: 'advanced',
      featured: true,
      tags: ['FCI', 'Structure', 'Owner education'],
      heroNote: 'The platform can explain the official standard, but it must not rewrite it or pretend to be a judging authority.',
      sections: [
        {
          heading: 'Separate fact from interpretation',
          body: 'Standard facts should remain visibly separate from USG interpretation. Owners need clarity on what is official, what is educational, and what is a platform trust decision.',
          bullets: ['Official facts cite source references.', 'USG notes explain platform meaning.', 'Certificates remain admin decisions, not automatic standard claims.'],
        },
        {
          heading: 'Useful reading zones',
          body: 'For most owners, the most useful standard areas are general appearance, proportions, temperament language, size, coat, color, and major faults. The full standard should remain the reference.',
        },
      ],
      keyFacts: [
        { label: 'Standard anchor', value: 'FCI Standard N°343' },
        { label: 'Owner purpose', value: 'Orientation before submission and public review' },
        { label: 'Boundary', value: 'Not a judge manual and not a certificate promise' },
      ],
      warnings: [
        'Do not turn the Knowledge article into automatic scoring logic.',
        'Do not imply that a registry entry guarantees a USG certificate.',
      ],
      sourceReferences: [sharedSources.fciStandard, sharedSources.fciBreed],
      relatedSlugs: ['cane-corso-history-and-identity', 'health-screening-and-responsible-care'],
      adminNotes: 'Keep as a public educational bridge. Future CMS should store official facts, editorial notes, and source references separately.',
    },
    {
      slug: 'health-screening-and-responsible-care',
      status: 'published',
      category: 'health',
      title: 'Health screening and responsible care',
      excerpt: 'A careful health-awareness article that explains screening orientation, daily care, and the line between education and veterinary advice.',
      reviewedLabel: 'USG editorial foundation • Step 30',
      readingLevel: 'advanced',
      tags: ['Health', 'Screening', 'Care'],
      heroNote: 'Health content is educational only. It supports owner awareness and should never replace veterinary advice.',
      sections: [
        {
          heading: 'Screening is part of trust',
          body: 'Health screening records help owners, breeders, and reviewers discuss risk responsibly. They do not make a Cane Corso perfect, but they make the profile more transparent.',
          bullets: ['Hips and elbows matter in large breeds.', 'Cardiac and patella checks can support responsible review.', 'Genetic screening references should be recorded clearly when available.'],
        },
        {
          heading: 'Care is everyday work',
          body: 'Responsible care includes weight management, controlled development, age-appropriate exercise, skin and coat observation, dental care, and calm handling around public environments.',
        },
      ],
      keyFacts: [
        { label: 'Content boundary', value: 'Education, not diagnosis' },
        { label: 'Platform role', value: 'Encourage transparent records and admin review' },
        { label: 'Owner action', value: 'Discuss health questions with a veterinarian' },
      ],
      warnings: [
        'Do not present platform health text as medical advice.',
        'Do not hide missing health information behind decorative profile design.',
      ],
      sourceReferences: [sharedSources.ccaaHealth, sharedSources.ofaChic],
      relatedSlugs: ['official-standard-owner-reading', 'training-socialization-and-public-safety'],
      adminNotes: 'Future admin workflow should require reviewed source references and visible health disclaimers for all health category articles.',
    },
    {
      slug: 'training-socialization-and-public-safety',
      status: 'published',
      category: 'training',
      title: 'Training, socialization, and public safety',
      excerpt: 'A practical safety article for living with a powerful guardian breed in family, city, travel, and public environments.',
      reviewedLabel: 'USG editorial foundation • Step 30',
      readingLevel: 'basic',
      tags: ['Training', 'Safety', 'Ownership'],
      heroNote: 'Public trust starts with calm control, early socialization, boundaries, and mature ownership.',
      sections: [
        {
          heading: 'Start before the problem appears',
          body: 'A Cane Corso needs calm exposure, clear household rules, leash manners, recall work, and stable routines before size and strength make every mistake more serious.',
          bullets: ['Reward calm behavior.', 'Avoid uncontrolled exposure.', 'Use qualified professional help when needed.'],
        },
        {
          heading: 'Public visibility is a responsibility',
          body: 'USG should promote mature ownership: lawful handling, respect for local rules, controlled transport, appropriate boarding, and careful choices around public spaces.',
        },
      ],
      keyFacts: [
        { label: 'Owner priority', value: 'Calm control and clear boundaries' },
        { label: 'Public layer', value: 'Safety before visibility' },
        { label: 'Professional help', value: 'Trainer support when behavior risk appears' },
      ],
      warnings: [
        'Do not romanticize aggression.',
        'Do not recommend public access where local rules or safety conditions are unclear.',
      ],
      sourceReferences: [sharedSources.akcBreed],
      relatedSlugs: ['cane-corso-history-and-identity', 'health-screening-and-responsible-care'],
      adminNotes: 'Useful bridge to future ecosystem services such as trainers, transport, boarding, and suitable public locations.',
    },

    {
      slug: 'cane-corso-standard-proportions',
      status: 'published',
      category: 'standard',
      title: 'Cane Corso exact proportions',
      excerpt: 'USG exact-proportions guide for rectangular outline, body length, head length, and correct Cane Corso profile.',
      reviewedLabel: 'USG Breed Standard • Step 35',
      readingLevel: 'expert',
      featured: true,
      tags: ['FCI', 'Proportions', 'USG standard'],
      heroNote: 'USG educational visualization based on the official breed standard. It does not replace a qualified judge or kennel-club document.',
      sections: [
        { heading: 'Rectangular outline', body: 'FCI describes the Cane Corso as rectangular and slightly longer than tall: body length is 11% greater than height at withers.', bullets: ['Body length = height at withers + 11%.', 'AKC cross-check: approximately 10% longer than tall.', 'The profile should remain powerful, athletic, and balanced.'] },
        { heading: 'Head length', body: 'The length of the head reaches 36% of the height at withers. AKC describes the head as approximately one third of height at withers.' },
      ],
      keyFacts: [
        { label: 'Body ratio', value: 'Length = height + 11%' },
        { label: 'Head ratio', value: 'Head length = 36% of height at withers' },
        { label: 'Boundary', value: 'USG educational visualization, not automatic judging' },
      ],
      warnings: ['Do not judge an individual Cane Corso from one photo alone.', 'This page explains standard proportions and does not promise registry publication or certification.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.akcStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-head-and-muzzle', 'cane-corso-head-axes', 'how-to-photograph-cane-corso-for-review'],
      adminNotes: 'Step 35 exact-proportions article. Keep the 11% and 36% ratios visible and source-backed.',
    },
    {
      slug: 'cane-corso-head-and-muzzle',
      status: 'published',
      category: 'standard',
      title: 'Head and muzzle ratio',
      excerpt: 'Precise USG explanation of the Cane Corso head: molossoid type, square muzzle, straight nasal bridge, and muzzle-to-skull ratio.',
      reviewedLabel: 'USG Breed Standard • Step 35',
      readingLevel: 'expert',
      featured: true,
      tags: ['Head', 'Muzzle', '1:2'],
      heroNote: 'The head is a breed-type anchor, but USG uses this article as education, not automatic scoring.',
      sections: [
        { heading: 'Muzzle to skull', body: 'The muzzle is noticeably shorter than the skull, with an approximate muzzle-to-skull ratio of 1:2.', bullets: ['Muzzle : skull ≈ 1 : 2.', 'Muzzle is strong and square.', 'Muzzle width equals muzzle length.'] },
        { heading: 'Shape and profile', body: 'The front part of the muzzle is flat, the lateral surfaces are parallel, and the nasal bridge is straight.' },
      ],
      keyFacts: [
        { label: 'Ratio', value: 'Muzzle : skull ≈ 1 : 2' },
        { label: 'Muzzle shape', value: 'Strong, square, as broad as long' },
        { label: 'Nasal bridge', value: 'Straight' },
      ],
      warnings: ['Do not exaggerate the muzzle shorter than functional breed type.', 'Do not present AI or diagram output as an official FCI illustration.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ukcStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-head-axes', 'cane-corso-standard-proportions'],
      adminNotes: 'Step 35 head/muzzle article.',
    },
    {
      slug: 'cane-corso-head-axes',
      status: 'published',
      category: 'standard',
      title: 'Head axes and common deviations',
      excerpt: 'USG visual guide to slightly convergent head axes and common deviations such as divergent axes, muzzle length issues, and excessive wrinkles.',
      reviewedLabel: 'USG Breed Standard • Step 35',
      readingLevel: 'expert',
      tags: ['Axes', 'Head type', 'Review helper'],
      heroNote: 'Slight convergence is an education point for review. It should support human evaluation, not replace it.',
      sections: [
        { heading: 'Slightly convergent planes', body: 'The upper longitudinal axes of skull and muzzle should be slightly convergent. This is an important breed-type reading point in profile.', bullets: ['Correct: slight convergence.', 'Not ideal as a USG teaching point: divergent axes.', 'Use clear side profile photos for review.'] },
        { heading: 'Common visual deviations', body: 'USG diagrams may show divergent axes, long muzzle, short muzzle, and excessive wrinkles as educational comparisons. They are not official FCI drawings.' },
      ],
      keyFacts: [
        { label: 'Correct orientation', value: 'Slight convergence' },
        { label: 'Review need', value: 'Clear side head profile' },
        { label: 'Boundary', value: 'Human-admin review only' },
      ],
      warnings: ['One angle or poor photo can distort perceived axes.', 'Educational diagrams should never become automatic rejection logic.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ukcStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-head-and-muzzle', 'how-to-photograph-cane-corso-for-review'],
      adminNotes: 'Step 35 axes article.',
    },
    {
      slug: 'cane-corso-front-structure',
      status: 'published',
      category: 'standard',
      title: 'Front structure and metacarpus alignment',
      excerpt: 'USG educational guide for reading front stance, balance, and inward or outward metacarpus deviation from clear front photos.',
      reviewedLabel: 'USG Breed Standard • Step 35',
      readingLevel: 'advanced',
      tags: ['Structure', 'Metacarpus', 'Photo review'],
      heroNote: 'Front structure guidance helps admins ask for better photos and owners understand why a correct standing view matters.',
      sections: [
        { heading: 'Why the front view matters', body: 'A clear front view can help show symmetry, balance, and metacarpus alignment. It should be read together with side view, movement, and overall condition.', bullets: ['Front standing view.', 'Natural stance, not forced pose.', 'Good light and straight camera angle.'] },
        { heading: 'Deviation language', body: 'USG may illustrate inward and outward deviation as visual education. Final conclusions require careful human review and should not be made from a single casual photo.' },
      ],
      keyFacts: [
        { label: 'Photo view', value: 'Front standing view' },
        { label: 'Focus', value: 'Symmetry and metacarpus alignment' },
        { label: 'Boundary', value: 'Not automatic scoring' },
      ],
      warnings: ['Surface, camera angle, and pose can make alignment look worse or better than reality.', 'Use this guide to request better photos, not to shame owners.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-standard-proportions', 'how-to-photograph-cane-corso-for-review'],
      adminNotes: 'Step 35 front-structure article.',
    },
    {
      slug: 'how-to-photograph-cane-corso-for-review',
      status: 'published',
      category: 'care',
      title: 'How to photograph your Cane Corso for review',
      excerpt: 'Owner photo guide for clearer USG review: side body, head profile, front and rear stance, and movement when possible.',
      reviewedLabel: 'USG Owner Guidance • Step 35',
      readingLevel: 'basic',
      featured: true,
      tags: ['Owner guide', 'Photos', 'Review'],
      heroNote: 'Good photos do not guarantee publication or certification, but they make responsible review clearer and fairer.',
      sections: [
        { heading: 'Five useful views', body: 'For a stronger review, prepare five clear views: whole body from the side, head profile, front stance, rear stance, and movement or gait when possible.', bullets: ['Side body view.', 'Head in profile.', 'Front and rear standing views.', 'Movement / gait if possible.'] },
        { heading: 'Make the image honest', body: 'Use natural light, keep the camera level, avoid heavy filters, and do not force an unnatural pose. Honest images help the platform protect trust.' },
      ],
      keyFacts: [
        { label: 'Minimum spirit', value: 'Clear and honest photos' },
        { label: 'Best set', value: 'Side, head, front, rear, movement' },
        { label: 'Platform role', value: 'Better admin review' },
      ],
      warnings: ['Do not manipulate photos to hide structure or condition.', 'Photo guidance is not a certificate promise.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-standard-proportions', 'cane-corso-head-and-muzzle', 'cane-corso-front-structure'],
      adminNotes: 'Step 35 owner guide article.',
    },
    {
      slug: 'admin-draft-knowledge-governance',
      status: 'draft',
      category: 'platform',
      title: 'Knowledge governance model',
      excerpt: 'Internal draft seed for the future admin workflow: who can write, review, publish, archive, and source-check Knowledge articles.',
      reviewedLabel: 'Internal draft • not public',
      readingLevel: 'expert',
      tags: ['Admin', 'Governance', 'Работен поток'],
      heroNote: 'This draft exists to test admin-only visibility and must not appear in the public Knowledge article list.',
      sections: [
        {
          heading: 'Future admin workflow',
          body: 'The future CMS should separate draft writing, admin review, source references, publishing, archiving, and updated review dates.',
        },
      ],
      keyFacts: [{ label: 'Visibility', value: 'Admin-only draft seed' }],
      warnings: ['Do not publish internal governance copy until the CMS workflow is implemented.'],
      sourceReferences: [],
      relatedSlugs: [],
      adminNotes: 'Admin-only draft lane seed. It proves that public routes filter non-published knowledge records.',
    },
  ],
  bg: [
    {
      slug: 'cane-corso-history-and-identity',
      status: 'published',
      category: 'history',
      title: 'История и идентичност на Cane Corso',
      excerpt: 'Кратка статия за името, италианските корени, пазителската линия и защо историята трябва да води към отговорно притежание.',
      reviewedLabel: 'USG редакционна основа • Step 30',
      readingLevel: 'basic',
      featured: true,
      tags: ['История', 'Италия', 'Идентичност'],
      heroNote: 'Историята трябва да подкрепя отговорността. Тя не трябва да превръща Cane Corso в символ на статус или декоративен лукс.',
      sections: [
        {
          heading: 'Името носи отговорност',
          body: 'Cane Corso не е общо име за едро куче. Това е сериозна италианска пазителска порода с работен произход, силно публично присъствие и нужда от отговорно водене.',
          bullets: ['Използвай името Cane Corso последователно.', 'Обяснявай идентичността преди промоцията.', 'Свързвай наследството със спокойно и безопасно притежание.'],
        },
        {
          heading: 'От наследство към доверие в платформата',
          body: 'USG трябва да използва историята като слой на доверие. Публичен профил, регистров запис или сертификат са по-силни, когато собственикът разбира породата зад документа.',
        },
      ],
      keyFacts: [
        { label: 'Произход', value: 'Италия / ориентация към Южна Италия' },
        { label: 'Идентичност', value: 'Пазителска и работна линия' },
        { label: 'USG употреба', value: 'Образователен контекст преди публична видимост' },
      ],
      warnings: [
        'Историята не доказва качеството на конкретно Cane Corso.',
        'Породното наследство не трябва да насърчава рисково публично поведение или притежание за статус.',
      ],
      sourceReferences: [sharedSources.fciStandard, sharedSources.fciBreed, sharedSources.akcBreed],
      relatedSlugs: ['official-standard-owner-reading', 'training-socialization-and-public-safety'],
      adminNotes: 'Безопасна публична статия. Бъдещият админ редактор може да заменя секции, но трябва да пази източниците и видимостта само за публикувани записи.',
    },
    {
      slug: 'official-standard-owner-reading',
      status: 'published',
      category: 'standard',
      title: 'Как собственикът да чете официалния стандарт',
      excerpt: 'Практичен мост между официалните породни факти и разбираемо обяснение за собственици, без да се заменя съдия или киноложки материал.',
      reviewedLabel: 'USG редакционна основа • Step 30',
      readingLevel: 'advanced',
      featured: true,
      tags: ['FCI', 'Структура', 'Образование'],
      heroNote: 'Платформата може да обяснява официалния стандарт, но не трябва да го пренаписва или да се представя като съдийски орган.',
      sections: [
        {
          heading: 'Разделяй факт от тълкуване',
          body: 'Фактите от стандарта трябва да стоят отделно от USG тълкуването. Собственикът трябва ясно да вижда кое е официално, кое е образователно и кое е решение на платформата.',
          bullets: ['Официалните факти имат източници.', 'USG бележките обясняват значението за платформата.', 'Сертификатът остава админ решение, не автоматично обещание.'],
        },
        {
          heading: 'Полезни зони за четене',
          body: 'За повечето собственици най-полезни са общият вид, пропорциите, темпераментът, размерът, козината, цветът и важните недостатъци. Пълният стандарт остава основната референция.',
        },
      ],
      keyFacts: [
        { label: 'Основна референция', value: 'FCI Standard N°343' },
        { label: 'Цел за собственика', value: 'Ориентация преди подаване и публичен преглед' },
        { label: 'Граница', value: 'Не е съдийско ръководство и не обещава сертификат' },
      ],
      warnings: [
        'Не превръщай Knowledge статията в автоматична оценка.',
        'Не внушавай, че регистров запис гарантира USG сертификат.',
      ],
      sourceReferences: [sharedSources.fciStandard, sharedSources.fciBreed],
      relatedSlugs: ['cane-corso-history-and-identity', 'health-screening-and-responsible-care'],
      adminNotes: 'Публичен образователен мост. Бъдещата система за управление трябва да пази отделно официални факти, редакционни бележки и източници.',
    },
    {
      slug: 'health-screening-and-responsible-care',
      status: 'published',
      category: 'health',
      title: 'Здравен скрининг и отговорна грижа',
      excerpt: 'Внимателна статия за здравна ориентация, ежедневна грижа и границата между образование и ветеринарен съвет.',
      reviewedLabel: 'USG редакционна основа • Step 30',
      readingLevel: 'advanced',
      tags: ['Здраве', 'Скрининг', 'Грижа'],
      heroNote: 'Здравното съдържание е само образователно. То подпомага информираността и не заменя ветеринарен лекар.',
      sections: [
        {
          heading: 'Скринингът е част от доверието',
          body: 'Здравните записи помагат на собственици, развъдчици и админи да говорят за риска отговорно. Те не правят Cane Corso перфектно, но правят профила по-прозрачен.',
          bullets: ['Тазобедрените стави и лактите са важни при едри породи.', 'Сърце и колене могат да подкрепят отговорен преглед.', 'Генетичните скрининги трябва да се записват ясно, когато са налични.'],
        },
        {
          heading: 'Грижата е ежедневна работа',
          body: 'Отговорната грижа включва контрол на теглото, развитие според възрастта, наблюдение на кожа и козина, зъбна грижа и спокойно водене в публична среда.',
        },
      ],
      keyFacts: [
        { label: 'Граница на съдържанието', value: 'Образование, не диагноза' },
        { label: 'Роля на платформата', value: 'Насърчава прозрачни записи и админ преглед' },
        { label: 'Действие за собственика', value: 'Здравните въпроси се обсъждат с ветеринар' },
      ],
      warnings: [
        'Не представяй платформено здравно съдържание като медицински съвет.',
        'Не скривай липсваща здравна информация зад красива визия на профила.',
      ],
      sourceReferences: [sharedSources.ccaaHealth, sharedSources.ofaChic],
      relatedSlugs: ['official-standard-owner-reading', 'training-socialization-and-public-safety'],
      adminNotes: 'Бъдещият админ работен поток трябва да изисква източници и видими предупреждения за здравни статии.',
    },
    {
      slug: 'training-socialization-and-public-safety',
      status: 'published',
      category: 'training',
      title: 'Обучение, социализация и публична безопасност',
      excerpt: 'Практична статия за живот с мощна пазителска порода в семейство, град, пътуване и публична среда.',
      reviewedLabel: 'USG редакционна основа • Step 30',
      readingLevel: 'basic',
      tags: ['Обучение', 'Безопасност', 'Притежание'],
      heroNote: 'Публичното доверие започва със спокоен контрол, ранна социализация, ясни граници и зряло притежание.',
      sections: [
        {
          heading: 'Започни преди да се появи проблем',
          body: 'Cane Corso има нужда от спокойна експозиция, ясни правила у дома, водене на повод, recall работа и стабилна рутина преди размерът и силата да направят всяка грешка по-сериозна.',
          bullets: ['Поощрявай спокойно поведение.', 'Избягвай неконтролирана експозиция.', 'Търси квалифицирана помощ при нужда.'],
        },
        {
          heading: 'Публичната видимост е отговорност',
          body: 'USG трябва да насърчава зряло притежание: законно водене, уважение към местните правила, контролиран транспорт, подходящи хотели за кучета и внимателен избор на публични места.',
        },
      ],
      keyFacts: [
        { label: 'Приоритет', value: 'Спокоен контрол и ясни граници' },
        { label: 'Публичен слой', value: 'Безопасност преди видимост' },
        { label: 'Професионална помощ', value: 'Треньор при поведенчески риск' },
      ],
      warnings: [
        'Не романтизирай агресията.',
        'Не препоръчвай публичен достъп, когато правилата или безопасността са неясни.',
      ],
      sourceReferences: [sharedSources.akcBreed],
      relatedSlugs: ['cane-corso-history-and-identity', 'health-screening-and-responsible-care'],
      adminNotes: 'Мост към бъдещи услуги в екосистемата: треньори, транспорт, хотели за кучета и подходящи места.',
    },

    {
      slug: 'cane-corso-standard-proportions',
      status: 'published',
      category: 'standard',
      title: 'Точни Cane Corso пропорции',
      excerpt: 'USG обяснение за правоъгълния силует, дължината на тялото, дължината на главата и точните пропорции зад правилния Cane Corso профил.',
      reviewedLabel: 'USG стандарт на породата • Step 35',
      readingLevel: 'expert',
      featured: true,
      tags: ['FCI', 'Пропорции', 'USG стандарт'],
      heroNote: 'Образователна USG визуализация, базирана на официалния стандарт на породата. Не замества квалифициран съдия или официален киноложки документ.',
      sections: [
        {
          heading: 'Правоъгълен силует',
          body: 'FCI стандартът описва Cane Corso като правоъгълен в силует и леко по-дълъг от висок: дължината на тялото е 11% по-голяма от височината при холката.',
          bullets: ['Дължина на тялото = височина при холката + 11%.', 'AKC cross-check: приблизително 10% по-дълъг от висок.', 'Профилът трябва да остане мощен, атлетичен и балансиран.'],
        },
        {
          heading: 'Дължина на главата',
          body: 'Дължината на главата достига 36% от височината при холката. AKC описва главата като приблизително една трета от височината при холката, което подкрепя същата насока за собственици.',
        },
      ],
      keyFacts: [
        { label: 'Съотношение тяло', value: 'Дължина = височина + 11%' },
        { label: 'Съотношение глава', value: 'Дължина на глава = 36% от височината при холката' },
        { label: 'Граница', value: 'USG образователна визуализация, не автоматично оценяване' },
      ],
      warnings: ['Не оценявай индивидуален Cane Corso само по една снимка.', 'Тази страница обяснява стандартни пропорции и не обещава публикуване в регистъра или сертификат.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.akcStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-head-and-muzzle', 'cane-corso-head-axes', 'how-to-photograph-cane-corso-for-review'],
      adminNotes: 'Step 35 exact-proportions article. Keep the 11% and 36% ratios visible and source-backed.',
    },
    {
      slug: 'cane-corso-head-and-muzzle',
      status: 'published',
      category: 'standard',
      title: 'Съотношение глава и муцуна',
      excerpt: 'Точно USG обяснение на Cane Corso глава: голям молосоиден тип, квадратна муцуна, прав носен профил и съотношение муцуна към череп.',
      reviewedLabel: 'USG стандарт на породата • Step 35',
      readingLevel: 'expert',
      featured: true,
      tags: ['Глава', 'Муцуна', '1:2'],
      heroNote: 'Главата е ключов елемент за породния тип, но USG използва тази статия като образование, не като автоматично оценяване.',
      sections: [
        { heading: 'Муцуна към череп', body: 'Муцуната е осезаемо по-къса от черепа, с приблизително съотношение муцуна към череп 1:2.', bullets: ['Муцуна : череп ≈ 1 : 2.', 'Муцуната е силна и квадратна.', 'Ширината на муцуната е равна на дължината.'] },
        { heading: 'Форма и профил', body: 'Предната част на муцуната е плоска, страничните повърхности са паралелни, а носният профил е прав.' },
      ],
      keyFacts: [
        { label: 'Съотношение', value: 'Муцуна : череп ≈ 1 : 2' },
        { label: 'Форма', value: 'Силна, квадратна, толкова широка, колкото е дълга' },
        { label: 'Носен профил', value: 'Прав' },
      ],
      warnings: ['Не преувеличавай муцуната извън функционалния породен тип.', 'Не представяй AI или USG диаграма като официална FCI илюстрация.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ukcStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-head-axes', 'cane-corso-standard-proportions'],
      adminNotes: 'Step 35 head/muzzle article.',
    },
    {
      slug: 'cane-corso-head-axes',
      status: 'published',
      category: 'standard',
      title: 'Оси на главата и чести отклонения',
      excerpt: 'USG визуален guide за леко събиращи се оси и отклонения като разминаващи се оси, дълга муцуна, къса муцуна и прекомерни бръчки.',
      reviewedLabel: 'USG стандарт на породата • Step 35',
      readingLevel: 'expert',
      tags: ['Оси', 'Тип глава', 'Преглед'],
      heroNote: 'Леката конвергенция е образователна точка за преглед. Тя подпомага човешката оценка, не я заменя.',
      sections: [
        { heading: 'Леко събиращи се равнини', body: 'Горните надлъжни оси на черепа и муцуната трябва леко да се събират. Това е важна точка при четене на главата в профил.', bullets: ['Правилно: лека конвергенция.', 'Неправилно като USG насока: разминаващи се оси.', 'За преглед е нужна ясна снимка на главата в профил.'] },
        { heading: 'Чести визуални отклонения', body: 'USG диаграмите могат да показват разминаващи се оси, дълга муцуна, къса муцуна и прекомерни бръчки като образователни сравнения, не като официални FCI рисунки.' },
      ],
      keyFacts: [
        { label: 'Правилна ориентация', value: 'Лека конвергенция' },
        { label: 'Нужда за преглед', value: 'Ясен страничен профил на глава' },
        { label: 'Граница', value: 'Само човешки админ преглед' },
      ],
      warnings: ['Един ъгъл или лоша снимка може да изкриви възприятието за осите.', 'Образователните диаграми не трябва да стават автоматична логика за отказ.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ukcStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-head-and-muzzle', 'how-to-photograph-cane-corso-for-review'],
      adminNotes: 'Step 35 axes article.',
    },
    {
      slug: 'cane-corso-front-structure',
      status: 'published',
      category: 'standard',
      title: 'Предна структура и подравняване на метакарпуса',
      excerpt: 'USG образователна насока за фронтална стойка, баланс и отклонения на метакарпуса навътре или навън.',
      reviewedLabel: 'USG стандарт на породата • Step 35',
      readingLevel: 'advanced',
      tags: ['Структура', 'Метакарпус', 'Снимки'],
      heroNote: 'Предната структура помага на админа да поиска по-добри снимки и на собственика да разбере защо правилната стойка има значение.',
      sections: [
        { heading: 'Защо фронталният изглед е важен', body: 'Ясният фронтален изглед може да помогне да се видят симетрия, баланс и подравняване на метакарпуса. Той трябва да се чете заедно със страничен изглед, движение и общо състояние.', bullets: ['Фронтална стойка.', 'Естествена стойка, без насилена поза.', 'Добра светлина и прав ъгъл на камерата.'] },
        { heading: 'Език за отклонение', body: 'USG може да илюстрира отклонение навътре и навън като визуално образование. Финалните изводи изискват внимателен човешки преглед.' },
      ],
      keyFacts: [
        { label: 'Снимка', value: 'Фронтална стойка' },
        { label: 'Фокус', value: 'Симетрия и метакарпус' },
        { label: 'Граница', value: 'Не е автоматична оценка' },
      ],
      warnings: ['Настилката, ъгълът на камерата и позата могат да изкривят видимото подравняване.', 'Използвай guide-а, за да поискаш по-добри снимки, не за да засрамваш собственици.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-standard-proportions', 'how-to-photograph-cane-corso-for-review'],
      adminNotes: 'Step 35 front-structure article.',
    },
    {
      slug: 'how-to-photograph-cane-corso-for-review',
      status: 'published',
      category: 'care',
      title: 'Как да снимаш своя Cane Corso за преглед',
      excerpt: 'Насока за собственици: тяло отстрани, глава в профил, фронтална и задна стойка, движение, когато е възможно.',
      reviewedLabel: 'USG насоки за собственика • Step 35',
      readingLevel: 'basic',
      featured: true,
      tags: ['Собственик', 'Снимки', 'Преглед'],
      heroNote: 'Добрите снимки не гарантират публикуване или сертификат, но правят отговорния преглед по-ясен и честен.',
      sections: [
        { heading: 'Пет полезни изгледа', body: 'За по-силен преглед подготви пет ясни изгледа: цяло тяло отстрани, глава в профил, фронтална стойка, задна стойка и движение или походка, ако е възможно.', bullets: ['Тяло отстрани.', 'Глава в профил.', 'Фронтална и задна стойка.', 'Движение / походка, ако е възможно.'] },
        { heading: 'Честна снимка', body: 'Използвай естествена светлина, дръж камерата хоризонтално, избягвай тежки филтри и не насилвай неестествена поза.' },
      ],
      keyFacts: [
        { label: 'Минимум', value: 'Ясни и честни снимки' },
        { label: 'Най-добър набор', value: 'Отстрани, глава, фронт, гръб, движение' },
        { label: 'Роля на платформата', value: 'По-добър админ преглед' },
      ],
      warnings: ['Не манипулирай снимки, за да скриеш структура или състояние.', 'Насоките за снимки не са обещание за сертификат.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-standard-proportions', 'cane-corso-head-and-muzzle', 'cane-corso-front-structure'],
      adminNotes: 'Step 35 owner guide article.',
    },
    {
      slug: 'admin-draft-knowledge-governance',
      status: 'draft',
      category: 'platform',
      title: 'Модел за управление на знанията',
      excerpt: 'Вътрешна чернова за бъдещия admin workflow: кой пише, преглежда, публикува, архивира и проверява източниците.',
      reviewedLabel: 'Вътрешна чернова • не е публична',
      readingLevel: 'expert',
      tags: ['Админ', 'Управление', 'Работен поток'],
      heroNote: 'Тази чернова тества admin-only видимост и не трябва да се показва в публичния списък със статии.',
      sections: [{ heading: 'Бъдещ админ работен поток', body: 'Бъдещата система за управление трябва да разделя писане на чернова, админ преглед, източници, публикуване, архивиране и дати на последен преглед.' }],
      keyFacts: [{ label: 'Видимост', value: 'Чернова само за админ' }],
      warnings: ['Не публикувай вътрешно съдържание за управление преди работният поток да е готов.'],
      sourceReferences: [],
      relatedSlugs: [],
      adminNotes: 'Начален запис за чернова само за админ. Доказва, че публичните адреси филтрират непубликувани записи.',
    },
  ],
  it: [
    {
      slug: 'cane-corso-history-and-identity',
      status: 'published',
      category: 'history',
      title: 'Storia e identità del Cane Corso',
      excerpt: 'Un articolo breve su nome, radici italiane, eredità da guardiano e responsabilità moderna.',
      reviewedLabel: 'Fondazione editoriale USG • Step 30',
      readingLevel: 'basic',
      featured: true,
      tags: ['Storia', 'Italia', 'Identità'],
      heroNote: 'La storia deve sostenere la responsabilità, non trasformare il Cane Corso in simbolo di status.',
      sections: [
        { heading: 'Il nome richiede responsabilità', body: 'Cane Corso non è un’etichetta generica per un cane grande. È una razza italiana seria, con presenza pubblica forte e bisogno di gestione matura.', bullets: ['Usare il nome Cane Corso con coerenza.', 'Spiegare l’identità prima della promozione.', 'Collegare eredità e sicurezza.'] },
        { heading: 'Dall’eredità alla fiducia', body: 'USG usa la storia come livello di fiducia: profilo pubblico, registro e certificato sono più forti quando il proprietario comprende la razza.' },
      ],
      keyFacts: [
        { label: 'Origine', value: 'Italia / orientamento Sud Italia' },
        { label: 'Identità', value: 'Guardiano e utilità' },
        { label: 'Uso USG', value: 'Educazione prima della visibilità pubblica' },
      ],
      warnings: ['La storia non prova la qualità di un singolo Cane Corso.', 'Non usare heritage copy per promuovere gestione rischiosa.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.fciBreed, sharedSources.akcBreed],
      relatedSlugs: ['official-standard-owner-reading', 'training-socialization-and-public-safety'],
      adminNotes: 'Articolo pubblico sicuro. Il futuro editor admin può sostituire sezioni preservando fonti e published-only visibility.',
    },
    {
      slug: 'official-standard-owner-reading',
      status: 'published',
      category: 'standard',
      title: 'Come leggere lo standard ufficiale',
      excerpt: 'Un ponte pratico tra fatti ufficiali di standard e spiegazione accessibile per proprietari.',
      reviewedLabel: 'Fondazione editoriale USG • Step 30',
      readingLevel: 'advanced',
      featured: true,
      tags: ['FCI', 'Struttura', 'Educazione'],
      heroNote: 'La piattaforma può spiegare lo standard ufficiale, ma non deve riscriverlo o sostituire autorità cinofile.',
      sections: [
        { heading: 'Separare fatto e interpretazione', body: 'I fatti dello standard devono restare separati dall’interpretazione USG. Il proprietario deve capire cosa è ufficiale, cosa è educativo e cosa è decisione della piattaforma.', bullets: ['I fatti ufficiali hanno fonti.', 'Le note USG spiegano il significato per la piattaforma.', 'Il certificato resta decisione admin.'] },
        { heading: 'Zone di lettura utili', body: 'Per molti proprietari sono utili aspetto generale, proporzioni, temperamento, taglia, mantello, colore e difetti principali. Lo standard completo resta la referenza.' },
      ],
      keyFacts: [
        { label: 'Ancora', value: 'FCI Standard N°343' },
        { label: 'Scopo', value: 'Orientamento prima di submission e revisione pubblica' },
        { label: 'Confine', value: 'Non è manuale giudice e non promette certificato' },
      ],
      warnings: ['Non trasformare l’articolo in scoring automatico.', 'Non implicare che un record registry garantisca certificato USG.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.fciBreed],
      relatedSlugs: ['cane-corso-history-and-identity', 'health-screening-and-responsible-care'],
      adminNotes: 'Ponte educativo pubblico. La futura CMS deve separare fatti ufficiali, note editoriali e fonti.',
    },
    {
      slug: 'health-screening-and-responsible-care',
      status: 'published',
      category: 'health',
      title: 'Screening salute e cura responsabile',
      excerpt: 'Un articolo di consapevolezza su screening, cura quotidiana e confine tra educazione e consiglio veterinario.',
      reviewedLabel: 'Fondazione editoriale USG • Step 30',
      readingLevel: 'advanced',
      tags: ['Salute', 'Screening', 'Cura'],
      heroNote: 'Il contenuto salute è solo educativo e non sostituisce il veterinario.',
      sections: [
        { heading: 'Lo screening fa parte della fiducia', body: 'I record salute aiutano proprietari, allevatori e admin a discutere il rischio con trasparenza. Non rendono un Cane Corso perfetto, ma rendono il profilo più chiaro.', bullets: ['Anche e gomiti contano nelle razze grandi.', 'Cuore e rotule possono aiutare una revisione responsabile.', 'Gli screening genetici vanno registrati chiaramente quando disponibili.'] },
        { heading: 'La cura è lavoro quotidiano', body: 'La cura responsabile include peso, sviluppo adeguato all’età, osservazione di pelle e mantello, denti e gestione calma in pubblico.' },
      ],
      keyFacts: [
        { label: 'Confine', value: 'Educazione, non diagnosi' },
        { label: 'Ruolo piattaforma', value: 'Incoraggiare record trasparenti e revisione admin' },
        { label: 'Azione proprietario', value: 'Parlare con un veterinario' },
      ],
      warnings: ['Non presentare contenuto salute come consiglio medico.', 'Non nascondere informazioni salute mancanti dietro design premium.'],
      sourceReferences: [sharedSources.ccaaHealth, sharedSources.ofaChic],
      relatedSlugs: ['official-standard-owner-reading', 'training-socialization-and-public-safety'],
      adminNotes: 'Il workflow admin futuro deve richiedere fonti e disclaimer visibile per articoli salute.',
    },
    {
      slug: 'training-socialization-and-public-safety',
      status: 'published',
      category: 'training',
      title: 'Training, socializzazione e sicurezza pubblica',
      excerpt: 'Articolo pratico per vivere con una razza guardiana potente in famiglia, città, viaggio e spazi pubblici.',
      reviewedLabel: 'Fondazione editoriale USG • Step 30',
      readingLevel: 'basic',
      tags: ['Training', 'Sicurezza', 'Ownership'],
      heroNote: 'La fiducia pubblica inizia con controllo calmo, socializzazione precoce, confini chiari e ownership matura.',
      sections: [
        { heading: 'Iniziare prima del problema', body: 'Un Cane Corso richiede esposizione calma, regole chiare, gestione al guinzaglio, richiamo e routine stabile prima che taglia e forza rendano ogni errore più serio.', bullets: ['Premiare calma.', 'Evitare esposizione incontrollata.', 'Usare supporto professionale quando serve.'] },
        { heading: 'La visibilità pubblica è responsabilità', body: 'USG deve promuovere gestione legale, rispetto delle regole locali, trasporto controllato, boarding adatto e scelta attenta degli spazi pubblici.' },
      ],
      keyFacts: [
        { label: 'Priorità', value: 'Controllo calmo e confini chiari' },
        { label: 'Livello pubblico', value: 'Sicurezza prima della visibilità' },
        { label: 'Aiuto professionale', value: 'Trainer quando appare rischio comportamentale' },
      ],
      warnings: ['Non romanticizzare aggressività.', 'Non raccomandare accesso pubblico quando regole o sicurezza non sono chiare.'],
      sourceReferences: [sharedSources.akcBreed],
      relatedSlugs: ['cane-corso-history-and-identity', 'health-screening-and-responsible-care'],
      adminNotes: 'Ponte verso servizi ecosystem futuri: trainer, trasporto, boarding e luoghi adatti.',
    },

    {
      slug: 'cane-corso-standard-proportions',
      status: 'published',
      category: 'standard',
      title: 'Proporzioni esatte del Cane Corso',
      excerpt: 'USG exact-proportions guide for rectangular outline, body length, head length, and correct Cane Corso profile.',
      reviewedLabel: 'USG Breed Standard • Step 35',
      readingLevel: 'expert',
      featured: true,
      tags: ['FCI', 'Proportions', 'USG standard'],
      heroNote: 'USG educational visualization based on the official breed standard. It does not replace a qualified judge or kennel-club document.',
      sections: [
        { heading: 'Rectangular outline', body: 'FCI describes the Cane Corso as rectangular and slightly longer than tall: body length is 11% greater than height at withers.', bullets: ['Body length = height at withers + 11%.', 'AKC cross-check: approximately 10% longer than tall.', 'The profile should remain powerful, athletic, and balanced.'] },
        { heading: 'Head length', body: 'The length of the head reaches 36% of the height at withers. AKC describes the head as approximately one third of height at withers.' },
      ],
      keyFacts: [
        { label: 'Body ratio', value: 'Length = height + 11%' },
        { label: 'Head ratio', value: 'Head length = 36% of height at withers' },
        { label: 'Boundary', value: 'USG educational visualization, not automatic judging' },
      ],
      warnings: ['Do not judge an individual Cane Corso from one photo alone.', 'This page explains standard proportions and does not promise registry publication or certification.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.akcStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-head-and-muzzle', 'cane-corso-head-axes', 'how-to-photograph-cane-corso-for-review'],
      adminNotes: 'Step 35 exact-proportions article. Keep the 11% and 36% ratios visible and source-backed.',
    },
    {
      slug: 'cane-corso-head-and-muzzle',
      status: 'published',
      category: 'standard',
      title: 'Rapporto testa e muso',
      excerpt: 'Precise USG explanation of the Cane Corso head: molossoid type, square muzzle, straight nasal bridge, and muzzle-to-skull ratio.',
      reviewedLabel: 'USG Breed Standard • Step 35',
      readingLevel: 'expert',
      featured: true,
      tags: ['Head', 'Muzzle', '1:2'],
      heroNote: 'The head is a breed-type anchor, but USG uses this article as education, not automatic scoring.',
      sections: [
        { heading: 'Muzzle to skull', body: 'The muzzle is noticeably shorter than the skull, with an approximate muzzle-to-skull ratio of 1:2.', bullets: ['Muzzle : skull ≈ 1 : 2.', 'Muzzle is strong and square.', 'Muzzle width equals muzzle length.'] },
        { heading: 'Shape and profile', body: 'The front part of the muzzle is flat, the lateral surfaces are parallel, and the nasal bridge is straight.' },
      ],
      keyFacts: [
        { label: 'Ratio', value: 'Muzzle : skull ≈ 1 : 2' },
        { label: 'Muzzle shape', value: 'Strong, square, as broad as long' },
        { label: 'Nasal bridge', value: 'Straight' },
      ],
      warnings: ['Do not exaggerate the muzzle shorter than functional breed type.', 'Do not present AI or diagram output as an official FCI illustration.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ukcStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-head-axes', 'cane-corso-standard-proportions'],
      adminNotes: 'Step 35 head/muzzle article.',
    },
    {
      slug: 'cane-corso-head-axes',
      status: 'published',
      category: 'standard',
      title: 'Assi della testa e deviazioni comuni',
      excerpt: 'USG visual guide to slightly convergent head axes and common deviations such as divergent axes, muzzle length issues, and excessive wrinkles.',
      reviewedLabel: 'USG Breed Standard • Step 35',
      readingLevel: 'expert',
      tags: ['Axes', 'Head type', 'Review helper'],
      heroNote: 'Slight convergence is an education point for review. It should support human evaluation, not replace it.',
      sections: [
        { heading: 'Slightly convergent planes', body: 'The upper longitudinal axes of skull and muzzle should be slightly convergent. This is an important breed-type reading point in profile.', bullets: ['Correct: slight convergence.', 'Not ideal as a USG teaching point: divergent axes.', 'Use clear side profile photos for review.'] },
        { heading: 'Common visual deviations', body: 'USG diagrams may show divergent axes, long muzzle, short muzzle, and excessive wrinkles as educational comparisons. They are not official FCI drawings.' },
      ],
      keyFacts: [
        { label: 'Correct orientation', value: 'Slight convergence' },
        { label: 'Review need', value: 'Clear side head profile' },
        { label: 'Boundary', value: 'Human-admin review only' },
      ],
      warnings: ['One angle or poor photo can distort perceived axes.', 'Educational diagrams should never become automatic rejection logic.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ukcStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-head-and-muzzle', 'how-to-photograph-cane-corso-for-review'],
      adminNotes: 'Step 35 axes article.',
    },
    {
      slug: 'cane-corso-front-structure',
      status: 'published',
      category: 'standard',
      title: 'Struttura frontale e allineamento metacarpo',
      excerpt: 'USG educational guide for reading front stance, balance, and inward or outward metacarpus deviation from clear front photos.',
      reviewedLabel: 'USG Breed Standard • Step 35',
      readingLevel: 'advanced',
      tags: ['Structure', 'Metacarpus', 'Photo review'],
      heroNote: 'Front structure guidance helps admins ask for better photos and owners understand why a correct standing view matters.',
      sections: [
        { heading: 'Why the front view matters', body: 'A clear front view can help show symmetry, balance, and metacarpus alignment. It should be read together with side view, movement, and overall condition.', bullets: ['Front standing view.', 'Natural stance, not forced pose.', 'Good light and straight camera angle.'] },
        { heading: 'Deviation language', body: 'USG may illustrate inward and outward deviation as visual education. Final conclusions require careful human review and should not be made from a single casual photo.' },
      ],
      keyFacts: [
        { label: 'Photo view', value: 'Front standing view' },
        { label: 'Focus', value: 'Symmetry and metacarpus alignment' },
        { label: 'Boundary', value: 'Not automatic scoring' },
      ],
      warnings: ['Surface, camera angle, and pose can make alignment look worse or better than reality.', 'Use this guide to request better photos, not to shame owners.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-standard-proportions', 'how-to-photograph-cane-corso-for-review'],
      adminNotes: 'Step 35 front-structure article.',
    },
    {
      slug: 'how-to-photograph-cane-corso-for-review',
      status: 'published',
      category: 'care',
      title: 'Come fotografare il tuo Cane Corso per review',
      excerpt: 'Owner photo guide for clearer USG review: side body, head profile, front and rear stance, and movement when possible.',
      reviewedLabel: 'USG Owner Guidance • Step 35',
      readingLevel: 'basic',
      featured: true,
      tags: ['Owner guide', 'Photos', 'Review'],
      heroNote: 'Good photos do not guarantee publication or certification, but they make responsible review clearer and fairer.',
      sections: [
        { heading: 'Five useful views', body: 'For a stronger review, prepare five clear views: whole body from the side, head profile, front stance, rear stance, and movement or gait when possible.', bullets: ['Side body view.', 'Head in profile.', 'Front and rear standing views.', 'Movement / gait if possible.'] },
        { heading: 'Make the image honest', body: 'Use natural light, keep the camera level, avoid heavy filters, and do not force an unnatural pose. Honest images help the platform protect trust.' },
      ],
      keyFacts: [
        { label: 'Minimum spirit', value: 'Clear and honest photos' },
        { label: 'Best set', value: 'Side, head, front, rear, movement' },
        { label: 'Platform role', value: 'Better admin review' },
      ],
      warnings: ['Do not manipulate photos to hide structure or condition.', 'Photo guidance is not a certificate promise.'],
      sourceReferences: [sharedSources.fciStandard, sharedSources.ccaaJudgesManual],
      relatedSlugs: ['cane-corso-standard-proportions', 'cane-corso-head-and-muzzle', 'cane-corso-front-structure'],
      adminNotes: 'Step 35 owner guide article.',
    },
    {
      slug: 'admin-draft-knowledge-governance',
      status: 'draft',
      category: 'platform',
      title: 'Modello governance Knowledge',
      excerpt: 'Bozza interna per il futuro workflow admin: scrittura, revisione, pubblicazione, archiviazione e controllo fonti.',
      reviewedLabel: 'Bozza interna • non pubblica',
      readingLevel: 'expert',
      tags: ['Admin', 'Governance', 'Работен поток'],
      heroNote: 'Questa bozza testa la visibilità admin-only e non deve apparire nel pubblico.',
      sections: [{ heading: 'Работен поток admin futuro', body: 'La futura CMS deve separare bozza, revisione admin, fonti, pubblicazione, archiviazione e data ultima revisione.' }],
      keyFacts: [{ label: 'Visibilità', value: 'Bozza solo admin' }],
      warnings: ['Non pubblicare contenuto governance interno prima del workflow CMS.'],
      sourceReferences: [],
      relatedSlugs: [],
      adminNotes: 'Admin-only draft lane seed. Dimostra che i route pubblici filtrano record non pubblicati.',
    },
  ],
};

function withLocale(locale: Locale, article: KnowledgeArticleSeed): KnowledgeArticle {
  return {
    ...article,
    locale,
  };
}

export function getKnowledgeArticles(locale: Locale): readonly KnowledgeArticle[] {
  return (articleSeeds[locale] ?? articleSeeds.en).map((article) => withLocale(locale, article));
}

export function getPublishedKnowledgeArticles(locale: Locale): readonly KnowledgeArticle[] {
  return getKnowledgeArticles(locale).filter((article) => article.status === 'published');
}

export function getAdminKnowledgeArticles(locale: Locale): readonly KnowledgeArticle[] {
  return getKnowledgeArticles(locale);
}

export function getPublishedKnowledgeArticleBySlug(locale: Locale, slug: string): KnowledgeArticle | null {
  return getPublishedKnowledgeArticles(locale).find((article) => article.slug === slug) ?? null;
}

export function getKnowledgeArticleBySlug(locale: Locale, slug: string): KnowledgeArticle | null {
  return getKnowledgeArticles(locale).find((article) => article.slug === slug) ?? null;
}

export function getKnowledgeArticleStaticParams(): Array<{ slug: string }> {
  const slugs = new Set<string>();
  for (const article of getPublishedKnowledgeArticles('en')) {
    slugs.add(article.slug);
  }

  return [...slugs].map((slug) => ({ slug }));
}

export function getRelatedPublishedKnowledgeArticles(locale: Locale, article: KnowledgeArticle): readonly KnowledgeArticle[] {
  const published = getPublishedKnowledgeArticles(locale);
  return article.relatedSlugs
    .map((slug) => published.find((item) => item.slug === slug))
    .filter((item): item is KnowledgeArticle => Boolean(item));
}
