import type { Dog } from '@cane-corso-platform/contracts';
import { DEMO_MEMBER_PROFILE_ID } from './demo-session.server';

export const myDogsMockData: Dog[] = [
  {
    id: 'dog_1',
    ownerProfileId: DEMO_MEMBER_PROFILE_ID,
    name: 'Ares Imperium Corso',
    slug: 'ares-imperium-corso',
    sex: 'male',
    dateOfBirth: '2023-04-15',
    color: 'Black Brindle',
    microchipNumber: '380260101234567',
    pedigreeNumber: 'FCI-BG-ARES-2023',
    shortDescription: 'Young male with balanced movement and strong head type.',
    longDescription: 'Structured mock entry for the premium member dashboard while the registry workspace is still under construction.',
    registryClass: 'owner_declared_cane_corso',
    pedigree: {},
    mainImageUrl: null,
    visibility: 'private',
    lifecycleStatus: 'draft',
    createdAt: '2026-04-01T10:15:00.000Z',
    updatedAt: '2026-04-11T09:30:00.000Z',
    publication: null,
  },
  {
    id: 'dog_2',
    ownerProfileId: DEMO_MEMBER_PROFILE_ID,
    name: 'Bellissima di Sofia',
    slug: 'bellissima-di-sofia',
    sex: 'female',
    dateOfBirth: '2022-11-02',
    color: 'Formentino',
    microchipNumber: '380260109876543',
    pedigreeNumber: 'FCI-BG-BELLA-2022',
    shortDescription: 'Elegant female profile prepared for registry review.',
    longDescription: 'Mock content used to visualize the future review and publication states in the member dog workspace.',
    registryClass: 'documented_without_pedigree',
    pedigree: {},
    mainImageUrl: null,
    visibility: 'public',
    lifecycleStatus: 'submitted',
    createdAt: '2026-03-15T13:20:00.000Z',
    updatedAt: '2026-04-10T18:05:00.000Z',
    publication: null,
  },
  {
    id: 'dog_3',
    ownerProfileId: DEMO_MEMBER_PROFILE_ID,
    name: 'Nero del Rhodope',
    slug: 'nero-del-rhodope',
    sex: 'male',
    dateOfBirth: '2021-08-21',
    color: 'Grey',
    microchipNumber: '380260102468135',
    pedigreeNumber: 'FCI-BG-NERO-2021',
    shortDescription: 'Public-ready profile positioned for featured publication.',
    longDescription: 'Represents a near-finished registry candidate used to shape the future visibility states and moderation flow.',
    registryClass: 'verified_pedigree',
    pedigree: {},
    mainImageUrl: null,
    visibility: 'public',
    lifecycleStatus: 'published',
    createdAt: '2026-02-20T08:40:00.000Z',
    updatedAt: '2026-04-09T16:10:00.000Z',
    publication: {
      publicSlug: 'nero-del-rhodope',
      publishedAt: '2026-04-09T16:10:00.000Z',
      certificateCode: 'USG-20260409-RHODOPE',
      verificationSlug: 'nero-del-rhodope-verify',
    },
  },
];
