INSERT INTO ecosystem_listings (
  owner_profile_id,
  listing_type,
  submission_channel,
  title,
  slug,
  category,
  short_description,
  long_description,
  country,
  city,
  website_url,
  phone,
  email,
  coverage_note,
  rules_note,
  logo_url,
  cover_image_url,
  status,
  is_featured,
  submitted_at,
  reviewed_at,
  published_at,
  review_note,
  created_at,
  updated_at
)
SELECT
  owner_profile_id,
  'partner_service',
  'official_listing',
  business_name,
  'partner-service-' || slug,
  category,
  short_description,
  long_description,
  country,
  city,
  website_url,
  phone,
  email,
  'Official Partner / Services profile approved for the Cane Corso ecosystem.',
  'Visible after administrator approval. Community ratings remain separate from official approval.',
  logo_url,
  cover_image_url,
  'published',
  is_featured,
  COALESCE(published_at, created_at, now()),
  COALESCE(published_at, updated_at, now()),
  COALESCE(published_at, updated_at, now()),
  'Backfilled from approved Partner / Services profile.',
  COALESCE(created_at, now()),
  COALESCE(updated_at, now())
FROM partners
WHERE status = 'approved'
ON CONFLICT (slug) DO UPDATE SET
  owner_profile_id = EXCLUDED.owner_profile_id,
  listing_type = EXCLUDED.listing_type,
  submission_channel = EXCLUDED.submission_channel,
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description,
  country = EXCLUDED.country,
  city = EXCLUDED.city,
  website_url = EXCLUDED.website_url,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  coverage_note = EXCLUDED.coverage_note,
  rules_note = EXCLUDED.rules_note,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  status = EXCLUDED.status,
  is_featured = EXCLUDED.is_featured,
  submitted_at = EXCLUDED.submitted_at,
  reviewed_at = EXCLUDED.reviewed_at,
  published_at = EXCLUDED.published_at,
  review_note = EXCLUDED.review_note,
  updated_at = EXCLUDED.updated_at;
